baseURL = "http://example.org/"
enableEmoji = true
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
googleAnalytics = "UA-XXXXXXXX-X"
languageCode = "en-us"
theme = "devfest-theme-hugo"
title = "InfoSec"
[languages.en]
languageName = "gb"
weight = 1
[languages.fr]
languageName = ""
weight = ""
[languages.fr.params]
description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."
[[menu.main]]
external = true
identifier = "jobs"
name = "Jobs"
url = "https://jobs.devfesttoulouse.fr/"
weight = "100"
[params]
appleTouchIcon = "/apple-touch-icon.png"
cfpUrl = "https://conference-hall.io/public/event/HJRThubF4uYPkb7jSUxi"
copyright = ":heart:️ We Are Legion"
date = "2019-10-03"
description = "InfoSec IIT Goa is a community working to bring a mindset geared towards cyber security with young minds"
email = "hash@dlkl.com"
favicon16 = "/favicon-16x16.png"
favicon32 = "/favicon-32x32.png"
googleWebmasterKey = "googleXXXXXXX"
images = ["/images/social-share.jpg"]
keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"
manifest = "/manifest.json"
safariPinnedTab = "/safari-pinned-tab.svg"
subscriptionUrl = "http://eepurl.com/dps1j5"
themeColor = "#673ab7"
title = "InfoSec IIT Goa"
[params.logos]
footer = "/uploads/infosec-trans.png"
header = "/uploads/infosec-trans.png"
jumbo = "/uploads/infosec-trans.png"
[taxonomies]
tag = "tags"
